{{ config(materialized='view') }}

SELECT
    _id AS ambassador_id,
    user_id,
    company_id,
    company_sector_id,
    entity_id AS ambassador_legacy_ambassador_entity_id,
    inactive_user_id AS ambassador_inactive_user_id,
    moderator_id AS ambassador_denormalized_last_moderator_user_id,
    contact_request_id,
    tag_ids as style_ids,
    created_at AS ambassador_created_at,
    updated_at AS ambassador_updated_at,
    converted_from_mentor_at AS ambassador_converted_from_mentor_at,
    first_approved_at AS ambassador_first_approved_at,
    career_started_at AS ambassador_career_started_at,
    first_published_at AS ambassador_first_published_at,
    published_at AS ambassador_last_published_at,
    first_publication_requested_at AS ambassador_first_publication_requested_at,
    publication_requested_at AS ambassador_last_publication_requested_at,
    first_publication_request_completion_at AS ambassador_first_publication_request_completion_at,
    last_restricted_at AS ambassador_last_restricted_at,
    last_unrestricted_at AS ambassador_last_unrestricted_at,
    unavailable_until_cache AS ambassador_becomes_available_or_iced_up_at,
    last_iced_up_at AS ambassador_last_iced_up_at,
    last_melted_at AS ambassador_last_melted_at,
    invitation.email AS ambassador_invitation_email,
    invitation.first_name AS ambassador_invitation_first_name,
    invitation.last_name AS ambassador_invitation_last_name,
    _type AS ambassador_type_raw,
    {{ ambassador_type("_type") }} AS ambassador_type,
    company_name AS ambassador_company_name,
    {{ company_size("company_size_cd") }} AS ambassador_company_size,
    company_attributes AS ambassador_company_attributes,
    company_logo_url_d AS ambassador_denormalized_company_logo_url,
    entity_name AS ambassador_legacy_ambassador_entity_name,
    converted_from_ambassador AS ambassador_is_converted_from_ambassador,
    independent_company AS ambassador_is_independent_company,
    company_logo_unavailable AS ambassador_is_company_logo_unavailable,
    moderated_at AS ambassador_denormalized_last_moderated_at,
    fun_sentence AS ambassador_fun_sentence,
    vip_account AS ambassador_is_vip_account,
    hidden_from_search AS ambassador_is_hidden_from_search,
    search_boost AS ambassador_search_boost,
    public_last_name AS ambassador_is_last_name_public,
    position AS ambassador_job_title,
    description AS ambassador_description,
    hide_how_it_works AS ambassador_is_how_it_works_banner_hidden,
    languages AS ambassador_languages_for_exchanging_with_students,
    published AS ambassador_is_published,
    last_publication_request_utm AS ambassador_last_publication_request_utm,
    promotions AS ambassador_promotions,
    educations AS ambassador_educations,
    recommended_qualifications AS ambassador_recommended_qualifications,
    mandatory_skills AS ambassador_mandatory_skills,
    restricted AS ambassador_is_restricted,
    restricted_reason AS ambassador_last_restricted_reason,
    unrestricted_reason AS ambassador_last_unrestricted_reason,
    iced_up AS ambassador_is_iced_up,
    ice_up_reason AS ambassador_last_iced_up_reason,
    max_meetings_per_month AS ambassador_max_appointments_per_month,
    publication_request_completion_percentage AS ambassador_publication_request_completion_percentag
FROM
    {{ source('marketplace', 'professionals') }}
