{{ config(materialized='view') }}

SELECT
    _id AS seeker_id,
    user_id,
    created_at AS seeker_profile_created_at,
    updated_at AS seeker_updated_at,
    first_completed_at AS seeker_profile_first_completed_at,
    last_edition_at AS seeker_profile_last_edited_at,
    soft_deleted_at AS seeker_last_soft_deleted_at,
    anonymized_at AS seeker_anonymized_at,
    _type AS seeker_type,
    educations AS seeker_educations,
    meeting_place AS seeker_meeting_place_address,
    coordinates AS seeker_meeting_place_coordinates,
    address_dataset AS seeker_meeting_place_address_dataset,
    normalized_phone AS seeker_normalized_phone,
    appointment_activities AS seeker_denormalized_appointment_reviews,
    description AS seeker_description,
    graduation_year AS seeker_graduation_year,
    complete AS seeker_is_profile_completed,
    subscribed_to_gatling AS seeker_is_subscribed_to_gatling,
    current_rating AS seeker_denormalized_average_rating_of_first_question,
    replied_conversations_count_cache AS seeker_replied_conversations_count_cache,
    affiliated_to_assignment_cache AS seeker_denormalized_is_involved_in_a_fdr,
    confirmed_appointment_with_professional_feedback_count AS seeker_denormalized_confirmed_appointment_with_ambassador_review_count,
    confirmed_appointment_count AS seeker_denormalized_confirmed_appointment_count,
    appointments_per_month AS seeker_denormalized_appointments_per_month,
    referrals_initiated_count AS seeker_denormalized_referrals_initiated_count,
    unique_profile_views_count_cache AS seeker_denormalized_unique_profile_views_count,
    last_mission_accomplished AS seeker_last_mission_accomplished,
FROM
    {{ source('marketplace', 'seekers') }}
