{{ config(materialized='view') }}

SELECT
    _id AS user_id,
    intercom_user_id,
    france_travail_id,
    address_dataset_id AS desired_meeting_address_id,
    widget_source.id as widget_source_id,
    created_at AS user_created_at,
    updated_at AS user_updated_at,
    soft_deleted_at as user_soft_deleted_at,
    anonymized_at AS user_anonymized_at,
    last_active_at_cache AS user_cache_last_active_at,
    reset_password_sent_at AS user_reset_password_sent_at,
    confirmed_at AS user_confirmed_at,
    confirmation_sent_at AS user_confirmation_sent_at,
    widget_source.id_added_at AS user_widget_source_added_at,
    ambivalence_activated AS user_is_ambivalent,
    first_name AS user_first_name,
    last_name AS user_last_name,
    email AS user_email,
    unconfirmed_email AS user_unconfirmed_email,
    normalized_phone AS user_normalized_phone,
    avatar AS user_avatar,
    languages AS user_languages,
    meeting_preferences AS user_meeting_preferences,
    meeting_place AS user_meeting_place,
    situation AS user_situation,
    situation_confirmed AS user_is_situation_confirmed_after_ambivalence,
    email_locale AS user_email_locale,
    referrer_code AS user_referrer_code,
    signed_up_as_high_school_teacher AS user_is_high_school_teacher,
    signed_up_as_oriane_ambassador AS user_is_oriane_ambassador,
    france_travail_id IS NOT NULL AS user_has_france_travail_connect,
    subscribed_to_news AS user_is_subscribed_to_red_carpets,
    videoconference_link_visible AS user_has_videoconference_enabled,
    soft_deleted_at IS NOT NULL AS user_is_soft_deleted,
    soft_deleted_reason AS user_soft_deleted_reason,
    anonymized_at IS NOT NULL AS user_is_anonymized,
    sign_up_utm AS user_sign_up_utm
FROM
    {{ source('marketplace', 'users') }}
